// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // ✅ FIXED
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows; // ✅ ADDED
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARTO_bC424e7HP_ERaaRNt7DM7k8Jwzy4',
    appId: '1:63548326296:android:d3c3d4afab9ebc073d2bed',
    messagingSenderId: '63548326296',
    projectId: 'phoneshop-8bbad',
    storageBucket: 'phoneshop-8bbad.firebasestorage.app',
  );

  // ✅ WEB (🔥 IMPORTANT: values Firebase Console mathi levana)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDQsXWD8ph603NINi1fFatcn8e-jOE0_k',
    appId: '1:63548326296:web:8c9cdc45a03f44f23d2bed',
    messagingSenderId: '63548326296',
    projectId: 'phoneshop-8bbad',
    storageBucket: 'phoneshop-8bbad.firebasestorage.app',
    authDomain: 'phoneshop-8bbad.firebaseapp.com',
  );

  // ✅ WINDOWS (same as android mostly)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDQsXWD8ph603NINi1fFatcn8e-jOE0_k',
    appId: '1:63548326296:web:e3c65a5185e8135f3d2bed', 
    messagingSenderId: '63548326296',
    projectId: 'phoneshop-8bbad',
    storageBucket: 'phoneshop-8bbad.firebasestorage.app',
  );
}
